### ISSUE TITLE
按照readme跑不起来了，

### ISSUE THREAD

**Issue by Redhair957** [TaoRuijie/TalkNet-ASD#68]
Traceback (most recent call last):
  File "trainTalkNet.py", line 86, in <module>
    main()
  File "trainTalkNet.py", line 32, in main
    preprocess_AVA(args)
  File "/root/autodl-tmp/TalkNet-ASD/utils/tools.py", line 68, in preprocess_AVA
    download_csv(args) # Take 1 minute 
  File "/root/autodl-tmp/TalkNet-ASD/utils/tools.py", line 81, in download_csv
    os.remove(args.dataPathAVA + '/csv.tar.gz')
FileNotFoundError: [Errno 2] No such file or directory: 'AVADataPath/csv.tar.gz'

**Comment by Redhair957** [comment]
先colab上面下载然后再存到本地
